package com.jy.dynamodb.exercise.domain;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.jy.dynamodb.exercise.config.DynamoDBConfig;
import lombok.*;

import java.time.LocalDateTime;

import static java.time.LocalDateTime.now;

@Getter
@Setter
@ToString
@NoArgsConstructor
@DynamoDBTable(tableName = "Comment")
public class Comment {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "byMentionId")
    private Integer mentionId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String content;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.BOOL)
    private boolean deleted;

    @DynamoDBAttribute
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "byMentionId")
    @DynamoDBTypeConverted(converter = DynamoDBConfig.LocalDateTimeConverter.class)
    private LocalDateTime createdAt;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DynamoDBConfig.LocalDateTimeConverter.class)
    private LocalDateTime deletedAt;

    @Builder
    public Comment(Integer mentionId, String name, String content) {
        this.mentionId = mentionId;
        this.name = name;
        this.content = content;
        this.createdAt = now();
        this.deleted = false;
    }

    public void update(String content) {
        this.content = content;
    }

    public void delete() {
        this.deleted = true;
        this.deletedAt = now();
    }

}
